export const LOCAL_TEXT = {
  balance: 'balance',
  quickActions: 'quickActions',
  dailyCheckin: 'dailyCheckin',
  inviteFriends: 'inviteFriends',
  fastTasks: 'fastTasks',
  comingSoon: 'comingSoon',
  allTasks: 'allTasks',
  friends: 'friends',
  wallet: 'wallet',
  tutorial: 'tutorial',
  profile: 'profile',
  openTelegram: 'openTelegram',
  whatXp: 'whatXp',
  whatXpText: 'whatXpText',
  copy: 'copy',
  share: 'share',
  claim: 'claim',
  go: 'go',
  next: 'next',
  skip: 'skip',
  done: 'done',
  connectTg: 'connectTg',
  connectTgSubtitle: 'connectTgSubtitle',
  enterPhone: 'enterPhone',
  enterCode: 'enterCode',
  enterPassword: 'enterPassword',
  permissions: 'permissions',
  disconnect: 'disconnect',
  tgConnected: 'tgConnected',
  actionLog: 'actionLog',
  lockedTask: 'lockedTask',
} as const;

export type LocalTextKey = keyof typeof LOCAL_TEXT;
