import { useEffect, useMemo, useState } from 'react';
import { Switch, Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BackButton, WebAppProvider, useExpand, useInitData, useWebApp } from '@vkruglikov/react-telegram-web-app';
import { Sheet } from 'react-modal-sheet';
import { I18nextProvider, useTranslation } from 'react-i18next';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import { CheckCircle2, ChevronRight, Copy, Gift, HelpCircle, Home, Lock, Share2, ShieldCheck, Sparkles, Target, Users, Wallet } from 'lucide-react';
import { ActionLogEntry, AutoTask, PermissionState, TgStatus, checkPassword, claimTask, disconnectTg, getActionLog, getAutoTasks, getMe, getPermissions, getTgStatus, login, sendCode, setRelogin, signIn, updatePermissions } from './lib/api';

const BOT_USERNAME = import.meta.env.VITE_BOT_USERNAME || 'hypefactory_bot';
const queryClient = new QueryClient();

i18n.use(initReactI18next).init({
  resources: {
    ru: { translation: {
      balance: 'XP Баланс', quickActions: 'Быстрые действия', dailyCheckin: 'Ежедневный вход', inviteFriends: 'Пригласить друзей', fastTasks: 'Избранные FAST TASKS', comingSoon: 'Скоро', allTasks: 'Все задания', friends: 'Друзья', wallet: 'Кошелёк', tutorial: 'Помощь', profile: 'Главная', openTelegram: 'Откройте через Telegram', whatXp: 'Что такое XP?', whatXpText: 'XP — энергия meme-factory: зарабатывайте её за соцдействия, рефералов и серии, затем открывайте дропы.', copy: 'Копировать', share: 'Поделиться', claim: 'Забрать', go: 'Перейти', next: 'Далее', skip: 'Пропустить', done: 'Готово', connectTg: 'Подключить Telegram', connectTgSubtitle: 'Зарабатывай токены автоматически', enterPhone: 'Введите номер телефона', enterCode: 'Введите код из Telegram', enterPassword: 'Введите пароль 2FA', permissions: 'Разрешения', disconnect: 'Отключить аккаунт', tgConnected: 'Telegram подключён', actionLog: 'История действий', lockedTask: 'Требует подключения TG',
      manage: 'Управление', earnMore: 'Заработай больше', emptyLog: 'Подключите Telegram чтобы видеть журнал действий', emptyTx: 'Здесь появятся ваши последние операции', referralLink: 'Реф-ссылка', invited: 'Приглашено', earned: 'Заработано XP', latestInvited: 'Недавно приглашены', recentTx: 'Последние операции', tonComingSoon: 'TonConnect скоро', buyTokensSoon: 'Покупка токенов — скоро', maskHint: 'Формат: +7 (___) ___-__-__', invalidCode: 'Неверный код. Попробуйте ещё раз.', codeSent: 'Код отправлен на', cloudPassword: 'Облачный пароль / 2FA', confirm: 'Подтвердить', connectToUnlock: 'Подключите Telegram чтобы разблокировать', codeFailed: 'Не удалось отправить код. Попробуйте ещё раз.', goAndBack: 'Откройте ссылку, через 5 секунд разблокируется кнопка «Забрать»', dailyClaimed: 'Сегодня выполнено', noTasks: 'Заданий нет', sendInvitesT: 'Рассылать приглашения моим контактам', sendInvitesS: '+1000 XP за принятое приглашение', autoCommentT: 'Автокомментарии в партнёрских каналах', autoCommentS: '+500 XP за комментарий', joinChannelsT: 'Подписываться на партнёрские каналы', joinChannelsS: '+300 XP за подписку', reactPostsT: 'Реагировать на партнёрские посты', reactPostsS: '+50 XP за реакцию', forwardMessagesT: 'Пересылать партнёрские сообщения', forwardMessagesS: 'Выкл. по умолчанию — повышенный риск', warningTag: 'предупреждение', whatHFCanDo: 'Что HypeFactory может делать с твоим аккаунтом', tgRentalActions: '9 MTProto-действий', allTasksTitle: 'Все задания', xpEnergy: '⚡ XP-энергия meme-фабрики', tutorial1t: 'Привет', tutorial1d: 'Тёмная meme-фабрика на связи.', tutorial2t: 'Зарабатывай XP', tutorial2d: 'Завершай быстрые задания и забирай награды.', tutorial3t: 'Зови друзей', tutorial3d: 'Делись реф-ссылкой и получай бонус XP.', enterFromTg: 'Откройте через Telegram', requiresInitData: 'Mini App работает только из Telegram WebApp.', xpStreak: '+50 XP серия', referralXp: '20% реферальный XP', socialActionsReady: '12 соцдействий готовы', nft: 'NFT', fastTasksCaps: 'FAST TASKS', passwordFailed: 'Ошибка проверки пароля'
    } },
  },
  fallbackLng: 'ru', interpolation: { escapeValue: false },
});

const cx = (...v: Array<string | false | undefined>) => v.filter(Boolean).join(' ');
const isTgEnv = () => Boolean(window.Telegram?.WebApp?.initData);

declare global { interface Window { Telegram?: any } }

type NavState = Record<string, unknown> | undefined;
function usePath() {
  const [path, setPath] = useState(location.pathname === '/' ? '/profile' : location.pathname);
  const [routeState, setRouteState] = useState<NavState>((history.state as NavState) || undefined);
  useEffect(() => {
    const onPop = () => { setPath(location.pathname === '/' ? '/profile' : location.pathname); setRouteState((history.state as NavState) || undefined); };
    addEventListener('popstate', onPop); return () => removeEventListener('popstate', onPop);
  }, []);
  const nav = (to: string, state?: NavState) => { history.pushState(state ?? null, '', to); setPath(to); setRouteState(state); };
  return [path, nav, routeState] as const;
}

function useAuthMe() { return useQuery({ queryKey: ['me'], queryFn: getMe, staleTime: 30_000 }); }
function useTgStatus() { return useQuery<TgStatus>({ queryKey: ['tg-status'], queryFn: getTgStatus, staleTime: 15_000 }); }

function AuthGate({ children, path, nav }: { children: React.ReactNode; path: string; nav: (to: string) => void }) {
  const [, initData] = useInitData();
  const webApp = useWebApp();
  const [, expand] = useExpand();
  useEffect(() => { expand(); }, [expand]);
  useEffect(() => { i18n.changeLanguage('ru'); }, []);
  useEffect(() => { const runLogin = () => login(initData || '', webApp?.initDataUnsafe?.start_param); setRelogin(runLogin); if (initData) runLogin(); }, [initData, webApp]);
  useEffect(() => { if (!initData && !isTgEnv() && path !== '/unauthorized') nav('/unauthorized'); }, [initData, path, nav]);
  return <>{children}</>;
}

function Header({ nav }: { nav: (to: string) => void }) { const { t } = useTranslation(); const { data: me } = useAuthMe(); const balance = me?.balance != null ? Number(me.balance).toLocaleString() : '—'; return <header className="fixed left-0 right-0 top-0 z-30 px-4 pt-[max(env(safe-area-inset-top),12px)] pb-3 bg-gradient-to-b from-[#0B0B0B] via-[#0B0B0B]/95 to-transparent"><div className="flex items-center justify-between"><button onClick={() => nav('/wallet')} className="rounded-2xl border border-[#38DBFF]/40 bg-[#090909]/90 px-4 py-2 shadow-[0_0_18px_rgba(56,219,255,.2)]"><span className="text-xs text-[#A8A8A8]">{t('balance')}</span><b className="ml-2 text-[#38DBFF]">{balance} XP</b></button></div></header>; }
function BalanceCard({ big = false }: { big?: boolean }) { const { t } = useTranslation(); const { data: me } = useAuthMe(); return <div className={cx('rounded-[28px] border border-[#38DBFF]/55 bg-[#090909] p-5 shadow-[0_0_24px_rgba(56,219,255,.28)] animate-[glow_3s_ease-in-out_infinite_alternate]', big && 'p-7')}><div className="flex items-center justify-between"><div><p className="text-[#A8A8A8] text-sm">{t('balance')}</p><h2 className={cx('font-black text-white', big ? 'text-5xl' : 'text-4xl')}>{me?.balance != null ? Number(me.balance).toLocaleString() : '—'}</h2><p className="text-[#38DBFF] font-semibold">Hype XP</p></div><div className="grid h-16 w-16 place-items-center rounded-3xl bg-[#38DBFF]/15 text-3xl">⚡</div></div></div>; }
function Card({ children, onClick, className }: { children: React.ReactNode; onClick?: () => void; className?: string }) { return <button onClick={onClick} className={cx('w-full rounded-3xl border border-white/10 bg-[#181818]/80 p-4 text-left backdrop-blur transition active:scale-[.98]', className)}>{children}</button>; }
function SectionTitle({ children }: { children: React.ReactNode }) { return <h3 className="mb-3 mt-6 text-sm font-black uppercase tracking-[.18em] text-[#38DBFF]">{children}</h3>; }
function PrimaryButton({ children, onClick, disabled, danger }: { children: React.ReactNode; onClick?: () => void; disabled?: boolean; danger?: boolean }) { return <button onClick={onClick} disabled={disabled} className={cx('w-full rounded-2xl py-4 font-black transition active:scale-[.99] disabled:opacity-50', danger ? 'border border-red-500/60 bg-red-500/10 text-red-300' : 'bg-[#38DBFF] text-black shadow-[0_0_22px_rgba(56,219,255,.45)]')}>{children}</button>; }

const maskPhone = (phone?: string) => phone ? phone.replace(/^(\+\d)\d+?(\d{2})$/, '$1 *** **$2') : '+7 *** **42';
const formatRuPhone = (input: string) => {
  const digits = input.replace(/\D/g, '').replace(/^8/, '7').replace(/^7?/, '7').slice(0, 11);
  const rest = digits.slice(1);
  const p1 = rest.slice(0, 3), p2 = rest.slice(3, 6), p3 = rest.slice(6, 8), p4 = rest.slice(8, 10);
  return `+7${p1 ? ` (${p1}` : ''}${p1.length === 3 ? ')' : ''}${p2 ? ` ${p2}` : ''}${p3 ? `-${p3}` : ''}${p4 ? `-${p4}` : ''}`;
};

function Profile({ nav }: { nav: (to: string) => void }) { const { t } = useTranslation(); const [open, setOpen] = useState(false); const { data: tg } = useTgStatus(); return <><BalanceCard/><div className={cx('mt-4 rounded-3xl border p-4', tg?.connected ? 'border-[#36D0A1]/50 bg-[#36D0A1]/10' : 'border-[#38DBFF]/50 bg-[#38DBFF]/10')}><div className="flex items-center justify-between gap-3"><div><b>{tg?.connected ? `✅ ${t('tgConnected')}` : `💎 ${t('earnMore')} — ${t('connectTg')}`}</b><p className="text-sm text-[#A8A8A8]">{tg?.connected ? maskPhone(tg.phone) : t('connectTgSubtitle')}</p></div><button onClick={() => nav(tg?.connected ? '/connect-tg/permissions' : '/connect-tg')} className="rounded-xl bg-[#38DBFF] px-3 py-2 text-sm font-black text-black">{tg?.connected ? t('manage') : t('connectTg')}</button></div></div><button onClick={() => setOpen(!open)} className="mt-4 flex w-full items-center justify-between rounded-2xl bg-[#181818] p-4"><span>{t('whatXp')}</span><ChevronRight className={cx('transition', open && 'rotate-90')}/></button>{open && <p className="px-2 pt-3 text-sm text-[#A8A8A8]">{t('whatXpText')}</p>}<SectionTitle>{t('quickActions')}</SectionTitle><div className="grid grid-cols-2 gap-3"><Card onClick={() => nav('/all-tasks')}><Gift className="text-[#36D0A1]"/><b>{t('dailyCheckin')}</b><p className="text-xs text-[#A8A8A8]">{t('xpStreak')}</p></Card><Card onClick={() => nav('/friends')}><Users className="text-[#38DBFF]"/><b>{t('inviteFriends')}</b><p className="text-xs text-[#A8A8A8]">{t('referralXp')}</p></Card></div><SectionTitle>{t('fastTasks')}</SectionTitle><Card onClick={() => nav('/all-tasks')} className="border-[#38DBFF]/50 shadow-[0_0_18px_rgba(56,219,255,.18)]"><div className="flex items-center justify-between"><div><b>{t('fastTasksCaps')}</b><p className="text-sm text-[#A8A8A8]">{t('socialActionsReady')}</p></div><Sparkles className="text-[#38DBFF]"/></div></Card><SectionTitle>{t('nft')}</SectionTitle><div className="grid grid-cols-3 gap-3">{['CYAN APE','MEME CHIP','XP PASS'].map(x=><div key={x} className="rounded-2xl border border-dashed border-white/15 bg-[#090909] p-3 text-center"><div className="mb-2 text-3xl">🧬</div><b className="text-xs">{x}</b><p className="text-[10px] text-[#A8A8A8]">{t('comingSoon')}</p></div>)}</div></>; }

function Tasks({ nav }: { nav: (to:string)=>void }) { const { t } = useTranslation(); const [selected, setSelected] = useState<AutoTask | null>(null); const [locked, setLocked] = useState<AutoTask | null>(null); const { data: tasks = [] } = useQuery({ queryKey: ['tasks'], queryFn: getAutoTasks }); const mtprotoActions = [{key:'invite_friend', ru:'Приглашение друга', xp:'+1000 XP'}, {key:'auto_comment', ru:'Автокомментарий', xp:'+500 XP'}, {key:'join_channel', ru:'Вступление в канал', xp:'+300 XP'}, {key:'react_post', ru:'Реакция на пост', xp:'+50 XP'}, {key:'forward_promo', ru:'Пересылка промо', xp:'+200 XP'}, {key:'chat_reply', ru:'Ответ в чате', xp:'+100 XP'}, {key:'post_story', ru:'Публикация Story', xp:'+1500 XP'}, {key:'vote_poll', ru:'Голос в опросе', xp:'+50 XP'}, {key:'leave_review', ru:'Отзыв', xp:'+300 XP'}]; const onTask = (task: AutoTask) => { if (task.requiresTgConnect && task.locked) setLocked(task); else setSelected(task); }; return <><SectionTitle>{t('allTasksTitle')}</SectionTitle><div className="space-y-3">{tasks.length === 0 && <p className="text-[#A8A8A8]">{t('noTasks')}</p>}{tasks.map(task=><button key={task.name} onClick={() => onTask(task)} className="flex w-full items-center gap-3 rounded-2xl border border-white/10 bg-[#181818] p-3 text-left"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#38DBFF]/10 text-xl">{task.locked ? '🔒' : task.icon}</span><span className="min-w-0 flex-1"><b>{task.title}</b><p className="truncate text-xs text-[#A8A8A8]">{task.requiresTgConnect && task.locked ? t('lockedTask') : task.description}</p></span><span className="rounded-full bg-[#38DBFF]/15 px-3 py-1 text-xs font-bold text-[#38DBFF]">+{task.reward} XP</span>{task.locked?<Lock className="text-yellow-300"/>:task.status==='CLAIMED'?<CheckCircle2 className="text-[#36D0A1]"/>:<ChevronRight className="text-[#A8A8A8]"/>}</button>)}</div><SectionTitle>{t('tgRentalActions')}</SectionTitle><div className="grid grid-cols-3 gap-2">{mtprotoActions.map(action => (<div key={action.key} className="rounded-2xl border border-[#38DBFF]/20 bg-[#181818] p-3 text-center"><p className="text-xs text-[#38DBFF] font-bold">{action.ru}</p><p className="text-[10px] text-[#A8A8A8]">{action.xp}</p></div>))}</div><TaskSheet task={selected} onClose={() => setSelected(null)}/><Sheet isOpen={!!locked} onClose={()=>setLocked(null)} detent="content"><Sheet.Backdrop onTap={()=>setLocked(null)} style={{background:'rgba(0,0,0,.68)'}}/><Sheet.Container style={{background:'#090909', borderTopLeftRadius:28, borderTopRightRadius:28, border:'1px solid rgba(56,219,255,.35)'}}><Sheet.Content><div className="px-5 py-8 text-center text-white"><div className="text-6xl">🔒</div><h2 className="mt-3 text-2xl font-black">{t('connectToUnlock')}</h2><p className="mt-2 text-[#A8A8A8]">{locked?.title}</p><PrimaryButton onClick={()=>{setLocked(null); nav('/connect-tg')}}>{t('connectTg')}</PrimaryButton></div></Sheet.Content></Sheet.Container></Sheet></>; }
function TaskSheet({ task, onClose }: { task: AutoTask | null; onClose: () => void }) { const { t } = useTranslation(); const qc = useQueryClient(); const [canClaim, setCanClaim] = useState(false); const mut = useMutation({ mutationFn: () => claimTask(task!.name), onSuccess: () => { qc.invalidateQueries({ queryKey: ['tasks'] }); qc.invalidateQueries({ queryKey: ['me'] }); onClose(); } }); useEffect(()=>{setCanClaim(false)},[task?.name]); if (!task) return null; const go = () => { window.open(task.url, '_blank'); setTimeout(()=>setCanClaim(true), 5000); }; return <Sheet isOpen={!!task} onClose={onClose} detent="content"><Sheet.Backdrop onTap={onClose} style={{background:'rgba(0,0,0,.68)'}}/><Sheet.Container style={{background:'#090909', borderTopLeftRadius:28, borderTopRightRadius:28, border:'1px solid rgba(56,219,255,.35)'}}><Sheet.Header/><Sheet.Content><div className="px-5 pb-8 text-white"><div className="mx-auto mb-4 grid h-20 w-20 place-items-center rounded-3xl bg-[#38DBFF]/15 text-5xl">{task.icon}</div><h2 className="text-center text-2xl font-black">{task.title}</h2><div className="mt-3 flex justify-center gap-2"><span className="rounded-full bg-[#38DBFF]/15 px-3 py-1 text-[#38DBFF]">+{task.reward} XP</span><span className="rounded-full bg-white/10 px-3 py-1">{task.status}</span></div><p className="mt-4 text-center text-[#A8A8A8]">{task.description}</p><button onClick={canClaim ? () => mut.mutate() : go} disabled={mut.isPending} className="mt-6 w-full rounded-2xl bg-[#38DBFF] py-4 font-black text-black shadow-[0_0_22px_rgba(56,219,255,.45)]">{canClaim ? t('claim') : t('go')}</button><p className="mt-2 text-center text-xs text-[#A8A8A8]">{t('goAndBack')}</p></div></Sheet.Content></Sheet.Container></Sheet>; }

function InputPhone({ nav }: { nav: (to:string, state?:NavState)=>void }) { const { t } = useTranslation(); const [phone,setPhone]=useState('+7 '); const [err,setErr]=useState(''); const mut=useMutation({ mutationFn:()=>sendCode(phone.replace(/[^+\d]/g,'')), onSuccess:(data)=>nav('/connect-tg/code',{phone:phone.replace(/[^+\d]/g,''), phoneCodeHash:data.phoneCodeHash || data.phone_code_hash || ''}), onError:()=>setErr(t('codeFailed')) }); return <div><div className="text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-3xl bg-[#38DBFF]/15 text-5xl">📲</div><h1 className="mt-4 text-3xl font-black">{t('connectTg')}</h1><p className="text-[#A8A8A8]">{t('connectTgSubtitle')}</p></div><SectionTitle>{t('enterPhone')}</SectionTitle><input value={phone} onChange={e=>setPhone(formatRuPhone(e.target.value))} inputMode="tel" className="w-full rounded-3xl border border-[#38DBFF]/40 bg-[#090909] p-5 text-2xl font-black text-white outline-none focus:shadow-[0_0_24px_rgba(56,219,255,.3)]" placeholder="+7 (___) ___-__-__"/><p className="mt-2 text-xs text-[#A8A8A8]">{t('maskHint')}</p>{err && <p className="mt-2 text-red-300">{err}</p>}<div className="mt-6"><PrimaryButton onClick={()=>mut.mutate()} disabled={mut.isPending || phone.replace(/\D/g,'').length<11}>{t('connectTg')}</PrimaryButton></div></div>; }
function InputCode({ nav, state }: { nav: (to:string, state?:NavState)=>void; state: NavState }) { const { t } = useTranslation(); const [digits,setDigits]=useState(['','','','','']); const [err,setErr]=useState(''); const phone=String(state?.phone||''); const hash=String(state?.phoneCodeHash||''); const code=digits.join(''); const mut=useMutation({ mutationFn:()=>signIn(phone,code,hash), onSuccess:(data)=>nav(data?.requires2FA?'/connect-tg/password':'/connect-tg/permissions',{phone}), onError:()=>setErr(t('invalidCode')) }); const setD=(i:number,v:string)=>{const d=[...digits]; d[i]=v.replace(/\D/g,'').slice(-1); setDigits(d); if(d[i]) document.getElementById(`otp-${i+1}`)?.focus();}; return <div><h1 className="text-3xl font-black">{t('enterCode')}</h1><p className="mt-2 text-[#A8A8A8]">{t('codeSent')} {maskPhone(phone)}</p><div className="my-8 grid grid-cols-5 gap-2">{digits.map((d,i)=><input key={i} id={`otp-${i}`} value={d} onChange={e=>setD(i,e.target.value)} inputMode="numeric" maxLength={1} autoFocus={i===0} className="h-16 rounded-2xl border border-[#38DBFF]/40 bg-[#090909] text-center text-3xl font-black outline-none focus:shadow-[0_0_18px_rgba(56,219,255,.35)]"/> )}</div>{err&&<p className="mb-3 text-red-300">{err}</p>}<PrimaryButton onClick={()=>mut.mutate()} disabled={mut.isPending||code.length<5}>{t('confirm')}</PrimaryButton></div>; }
function PasswordScreen({ nav }: { nav: (to:string)=>void }) { const { t }=useTranslation(); const [password,setPassword]=useState(''); const [err,setErr]=useState(''); const mut=useMutation({ mutationFn:()=>checkPassword(password), onSuccess:()=>nav('/connect-tg/permissions'), onError:()=>setErr(t('passwordFailed')) }); return <div><h1 className="text-3xl font-black">{t('enterPassword')}</h1><p className="mt-2 text-[#A8A8A8]">{t('cloudPassword')}</p><input type="password" value={password} onChange={e=>setPassword(e.target.value)} className="my-6 w-full rounded-3xl border border-[#38DBFF]/40 bg-[#090909] p-5 text-xl font-bold text-white outline-none" placeholder="••••••••" />{err&&<p className="mb-3 text-red-300">{err}</p>}<PrimaryButton onClick={()=>mut.mutate()} disabled={mut.isPending||password.length<2}>{t('confirm')}</PrimaryButton></div>; }
function PermissionsScreen({ nav }: { nav: (to:string)=>void }) { const { t }=useTranslation(); const qc=useQueryClient(); const {data:perms}=useQuery({queryKey:['tg-permissions'],queryFn:getPermissions}); const [local,setLocal]=useState<PermissionState|undefined>(); useEffect(()=>{if(perms) setLocal(perms)},[perms]); const mut=useMutation({mutationFn:(next:PermissionState)=>updatePermissions(next), onSuccess:()=>qc.invalidateQueries({queryKey:['tg-permissions']})}); const disc=useMutation({mutationFn:disconnectTg,onSuccess:()=>{qc.invalidateQueries({queryKey:['tg-status']});nav('/profile')}}); const permMeta = [['sendInvites','✉️',t('sendInvitesT'),t('sendInvitesS'),true], ['autoComment','💬',t('autoCommentT'),t('autoCommentS'),true], ['joinChannels','📢',t('joinChannelsT'),t('joinChannelsS'),true], ['reactPosts','❤️',t('reactPostsT'),t('reactPostsS'),true], ['forwardMessages','⚠️',t('forwardMessagesT'),t('forwardMessagesS'),false]] as const; const current=local||perms||{}; const toggle=(key:string,on:boolean)=>{const next={...current,[key]:on}; setLocal(next); mut.mutate(next);}; return <div><div className="text-center"><ShieldCheck className="mx-auto text-[#38DBFF]" size={58}/><h1 className="mt-4 text-2xl font-black">{t('whatHFCanDo')}</h1><p className="text-[#A8A8A8]">{t('permissions')}</p></div><div className="mt-6 space-y-3">{permMeta.map(([key,icon,title,sub,def])=><div key={key} className={cx('rounded-3xl border bg-[#181818] p-4', key==='forwardMessages'?'border-yellow-400/40':'border-white/10')}><div className="flex items-center justify-between gap-3"><div className="flex gap-3"><span className="text-2xl">{icon}</span><div><b>{title}</b><p className="text-xs text-[#A8A8A8]">{sub}</p>{key==='forwardMessages'&&<span className="mt-2 inline-block rounded-full bg-yellow-400/15 px-2 py-1 text-[10px] font-bold text-yellow-300">{t('warningTag')}</span>}</div></div><Switch checked={Boolean(current[key] ?? def)} onCheckedChange={on=>toggle(key,on)}/></div></div>)}</div><div className="mt-6 grid gap-3"><PrimaryButton onClick={()=>nav('/all-tasks')}>{t('done')}</PrimaryButton><PrimaryButton danger onClick={()=>disc.mutate()} disabled={disc.isPending}>🔴 {t('disconnect')}</PrimaryButton></div></div>; }
function Friends() { const { t } = useTranslation(); const { data: me } = useAuthMe(); const ref = me?.refCode ? `https://t.me/${BOT_USERNAME}?startapp=ref_${me.refCode}` : ''; const webApp = useWebApp(); return <><Card className="border-[#38DBFF]/40"><p className="text-xs text-[#A8A8A8]">{t('referralLink')}</p><b className="break-all text-[#38DBFF]">{ref || 'Загрузка…'}</b><div className="mt-4 grid grid-cols-2 gap-3"><button className="rounded-2xl bg-white/10 py-3" onClick={() => ref && navigator.clipboard?.writeText(ref)} disabled={!ref}><Copy className="mx-auto mb-1"/> {t('copy')}</button><button className="rounded-2xl bg-[#38DBFF] py-3 text-black disabled:opacity-50" disabled={!ref} onClick={() => ref && webApp?.openTelegramLink?.(`https://t.me/share/url?url=${encodeURIComponent(ref)}`)}><Share2 className="mx-auto mb-1"/> {t('share')}</button></div></Card><div className="mt-4 grid grid-cols-2 gap-3"><Card><b className="text-3xl">{me?.invitedCount ?? 0}</b><p className="text-[#A8A8A8]">{t('invited')}</p></Card><Card><b className="text-3xl">{me?.earnedFromRefs ?? 0}</b><p className="text-[#A8A8A8]">{t('earned')}</p></Card></div><SectionTitle>{t('latestInvited')}</SectionTitle>{(me?.latestInvited ?? []).slice(0,5).map((name,i)=><div key={name} className="mb-2 flex items-center gap-3 rounded-2xl bg-[#181818] p-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#38DBFF]/15">{i+1}</span><b>{name}</b></div>)}</>; }
function WalletPage() { const {t}=useTranslation(); const {data:log=[]}=useQuery<ActionLogEntry[]>({queryKey:['tg-action-log'],queryFn:getActionLog}); return <><BalanceCard big/><button onClick={() => alert(t('tonComingSoon'))} className="mt-4 w-full rounded-2xl border border-[#38DBFF]/40 bg-[#181818] py-4 font-bold text-[#38DBFF]">{t('tonComingSoon')}</button><button disabled className="mt-3 w-full rounded-2xl bg-white/5 py-4 text-[#A8A8A8]">{t('buyTokensSoon')}</button><SectionTitle>{t('actionLog')}</SectionTitle><div className="space-y-2">{log.length === 0 && <p className="text-[#A8A8A8]">{t('emptyLog')}</p>}{log.slice(0,20).map(entry=><div key={entry.id} className="flex items-center gap-3 rounded-2xl bg-[#181818] p-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#38DBFF]/10 text-xl">{entry.icon}</span><div className="min-w-0 flex-1"><b className="block truncate">{entry.description}</b><p className="text-xs text-[#A8A8A8]">{entry.timestamp}</p></div><span className="rounded-full bg-[#36D0A1]/15 px-3 py-1 text-xs font-black text-[#36D0A1]">+{entry.xp} XP</span></div>)}</div><SectionTitle>{t('recentTx')}</SectionTitle><p className="text-[#A8A8A8]">{t('emptyTx')}</p></>; }
function Tutorial({ nav }: { nav: (to: string) => void }) { const { t } = useTranslation(); const slides = [{t:t('tutorial1t'),d:t('tutorial1d'),e:'👋'}, {t:t('tutorial2t'),d:t('tutorial2d'),e:'⚡'}, {t:t('tutorial3t'),d:t('tutorial3d'),e:'🧲'}]; const [i,setI]=useState(0); const done=()=>{localStorage.setItem('onboardCompleted','1'); nav('/profile')}; return <div className="flex min-h-[58vh] flex-col items-center justify-center text-center"><div className="text-7xl">{slides[i].e}</div><h1 className="mt-5 text-3xl font-black">{slides[i].t}</h1><p className="mt-2 text-[#A8A8A8]">{slides[i].d}</p><div className="mt-8 flex gap-2">{slides.map((_,n)=><span key={n} className={cx('h-2 rounded-full transition-all', n===i?'w-8 bg-[#38DBFF]':'w-2 bg-white/20')}/>)}</div><div className="mt-8 grid w-full grid-cols-2 gap-3"><button onClick={done} className="rounded-2xl bg-white/10 py-4">{t('skip')}</button><button onClick={() => i===2?done():setI(i+1)} className="rounded-2xl bg-[#38DBFF] py-4 font-black text-black">{i===2?t('done'):t('next')}</button></div></div>; }
function Unauthorized() { const { t } = useTranslation(); return <main className="grid h-[100dvh] place-items-center bg-[#0B0B0B] px-6 text-center text-white"><div><div className="mx-auto grid h-28 w-28 place-items-center rounded-[2rem] border border-[#38DBFF]/40 bg-[#38DBFF]/10 text-6xl">🤖</div><h1 className="mt-6 text-3xl font-black">{t('openTelegram')}</h1><p className="mt-3 text-[#A8A8A8]">{t('requiresInitData')}</p></div></main>; }
const tabs = [['/profile', Home, 'profile'], ['/all-tasks', Target, 'allTasks'], ['/friends', Users, 'friends'], ['/wallet', Wallet, 'wallet'], ['/tutorial', HelpCircle, 'tutorial']] as const;
function BottomNav({ path, nav }: { path: string; nav: (to:string)=>void }) { const { t } = useTranslation(); if (path==='/unauthorized'||path.startsWith('/connect-tg')) return null; return <nav className="fixed bottom-0 left-0 right-0 z-30 grid h-[10vh] grid-cols-5 border-t border-white/10 bg-[#090909]/95 px-2 backdrop-blur">{tabs.map(([to,Icon,label])=>{const active=path===to; return <button key={to} onClick={()=>nav(to)} className={cx('flex flex-col items-center justify-center gap-1 text-xs transition', active?'scale-105 text-[#38DBFF]':'text-[#A8A8A8]')}><Icon size={20}/>{t(label)}</button>})}</nav>; }
function Shell() { const [path, nav, routeState] = usePath(); const showBack = path === '/tutorial' || path === '/all-tasks' || path.startsWith('/connect-tg'); const screen = useMemo(() => { if (path === '/all-tasks') return <Tasks nav={nav} />; if (path === '/friends') return <Friends />; if (path === '/wallet') return <WalletPage />; if (path === '/tutorial') return <Tutorial nav={nav} />; if (path === '/connect-tg') return <InputPhone nav={nav} />; if (path === '/connect-tg/code') return <InputCode nav={nav} state={routeState} />; if (path === '/connect-tg/password') return <PasswordScreen nav={nav} />; if (path === '/connect-tg/permissions') return <PermissionsScreen nav={nav} />; if (path === '/unauthorized') return <Unauthorized />; return <Profile nav={nav} />; }, [path, nav, routeState]); if (path === '/unauthorized') return screen; return <AuthGate path={path} nav={nav}>{showBack && <BackButton onClick={() => nav(path.startsWith('/connect-tg') ? '/profile' : '/profile')} />}<div id="app-shell" className="relative flex h-[100dvh] flex-col overflow-hidden bg-[#0B0B0B] text-white"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_20%_10%,rgba(56,219,255,.18),transparent_35%),radial-gradient(circle_at_85%_30%,rgba(54,208,161,.1),transparent_30%)]" /><Header nav={nav} /><main className="relative z-10 flex-1 overflow-y-auto px-4 pb-[12vh] pt-[calc(env(safe-area-inset-top,0px)+88px)]">{screen}</main><BottomNav path={path} nav={nav} /></div></AuthGate>; }
export default function App() { return <WebAppProvider options={{ smoothButtonsTransition: true }}><QueryClientProvider client={queryClient}><I18nextProvider i18n={i18n}><Theme appearance="dark" accentColor="cyan" grayColor="slate" radius="large"><Shell /></Theme></I18nextProvider></QueryClientProvider></WebAppProvider>; }
